apiVersion: apps/v1
kind: Deployment
metadata:
  name: wannacry-lab-${pod_hash}
  labels:
    app: wannacry-lab-${pod_hash}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wannacry-lab-${pod_hash}
  template:
    metadata:
      name: wannacry-lab-${pod_hash}
      labels:
        app: wannacry-lab-${pod_hash}
      annotations:
        container.apparmor.security.beta.kubernetes.io/mininet-sec: unconfined
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ${allowed_nodes}
      containers:
      - name: mininet-sec
        image: hackinsdn/mininet-sec:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8050
        - containerPort: 8181
        - containerPort: 8006
        - containerPort: 8007
        - containerPort: 8008
        - containerPort: 8009
        command: ["/usr/bin/tini", "--", "/bin/sh", "-x", "-c"]
        args: 
        - git clone --branch main https://github.com/FelipeR-UFBA/lab-wannacry.git /tmp/labs;
          mkdir -p /root/labs/;
          mv /tmp/labs/topo-wannacry.yml /root/labs/topo-wannacry.yml;
          rm -rf /tmp/labs;
          cd /root/labs/;
          service openvswitch-switch start;
          tmux new-sess -d -s mnsec mnsec --topofile topo-wannacry.yml;
          sleep infinity;
        workingDir: /root/labs/
        env: 
        - name: K8S_POD_HASH
          value: ${pod_hash}
        - name: K8S_NODE_AFFINITY
          value: ${allowed_nodes_str}
        - name: K8S_PROXY_CERT_FILE
          value: /usr/local/etc/mnsec-proxy-ca.crt
        - name: K8S_PROXY_HOST
          value: mnsec-proxy-service.hackinsdn.svc.cnacv5
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_MODULE", "SYS_ADMIN"]
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
        - name: mnsec-proxy-ca-volume
          mountPath: /usr/local/etc/mnsec-proxy-ca.crt
          readOnly: true
          subPath: ca.crt
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: mnsec-proxy-ca-volume
        configMap:
          defaultMode: 0600
          name: mnsec-proxy-ca-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: wannacry-lab-${pod_hash}
  labels:
    app: wannacry-lab-${pod_hash}
spec:
  type: NodePort
  ports:
  - port: 8050
    targetPort: 8050
    name: http-mininet-sec
  - port: 8181
    targetPort: 8181
    name: http-kytos
  - port: 8006
    targetPort: 8006
    name: http-NoVNC-Atacante
  - port: 8007
    targetPort: 8007
    name: http-NoVNC-Vitima1
  - port: 8008
    targetPort: 8008
    name: http-NoVNC-Vitima2
  - port: 8009
    targetPort: 8009
    name: http-NoVNC-Vitima3
  selector:
    app: wannacry-lab-${pod_hash}
